---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R images/ $DEPLOYPATH
    - /bin/cp -R 3d-visualisering-eiendom/ $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp favicon.svg $DEPLOYPATH
    - /bin/cp llms.txt $DEPLOYPATH
    - /bin/cp prisliste.pdf $DEPLOYPATH
    - /bin/cp norgespakkene-2026.pdf $DEPLOYPATH
    - /bin/cp premiumpakkene-2026.pdf $DEPLOYPATH
