---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R images/ $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp favicon.svg $DEPLOYPATH
    - /bin/cp llms.txt $DEPLOYPATH
